/**
 * Minimal markdown-to-HTML formatter for chat messages and guideline summaries.
 *
 * The input is untrusted (LLM output, PDF-derived guideline text, user-typed
 * queries), so ALL HTML is escaped first — only the markup generated by the
 * transforms below can ever reach the DOM.
 */

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function formatMessageText(text: string): string {
  if (!text) return '';
  return escapeHtml(text)
    // Replace markdown headings (### and ##)
    .replace(/^###\s+(.+)$/gm, '<h3 class="text-xs font-bold text-teal-400 mt-3 mb-1.5 uppercase tracking-wider">$1</h3>')
    .replace(/^##\s+(.+)$/gm, '<h2 class="text-sm font-bold text-teal-400 mt-4 mb-2 uppercase tracking-wide border-b border-slate-800 pb-1.5">$1</h2>')
    // Replace bold markdown
    .replace(/\*\*(.*?)\*\*/g, '<strong class="text-slate-100 font-semibold">$1</strong>')
    // Replace page markdown references
    .replace(/\[Page (.*?)\]/g, '<span class="text-teal-400 font-bold underline cursor-pointer hover:text-teal-350">[Pg $1]</span>')
    // Replace online search button link format
    .replace(/\[Online AI Search\]\(\/ask-online-ai\)/g, '<button class="bg-teal-500 hover:bg-teal-650 active:scale-95 text-slate-950 font-bold px-3 py-1.5 rounded-lg text-xxs mt-2 transition-all block online-search-btn shadow-md shadow-teal-500/10">Run Edge LLM Search ⚡</button>')
    // Format bullet lists (lines starting with -, *, or •)
    .replace(/^(?:-|•|\*)\s+(.+)$/gm, '<div class="flex items-start gap-2 my-1.5 ml-2 text-slate-300"><span class="text-teal-400 mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-teal-400"></span><span class="flex-1">$1</span></div>')
    // Format numbered lists (lines starting with number followed by dot)
    .replace(/^(\d+)\.\s+(.+)$/gm, '<div class="flex items-start gap-2 my-1.5 ml-2 text-slate-300"><span class="text-teal-400 font-bold shrink-0 font-mono">$1.</span><span class="flex-1">$2</span></div>');
}
