/**
 * Safe evaluator for dose-calculator formulas.
 *
 * Calculator schemas are generated by an LLM and stored in R2, so their
 * formulas are untrusted input — they must never reach `eval`/`new Function`.
 * This module parses a deliberately tiny expression grammar instead:
 *
 *   numbers, single/double-quoted string literals, scope identifiers,
 *   + - * / %, comparisons (> < >= <= === !== == !=), && || !,
 *   ternary `cond ? a : b`, parentheses, and an allowlist of Math functions.
 *
 * Anything outside that grammar throws a FormulaError.
 */

export class FormulaError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'FormulaError';
  }
}

const MATH_FUNCTIONS: Record<string, (...args: number[]) => number> = {
  abs: Math.abs,
  ceil: Math.ceil,
  floor: Math.floor,
  round: Math.round,
  trunc: Math.trunc,
  sign: Math.sign,
  sqrt: Math.sqrt,
  pow: Math.pow,
  min: Math.min,
  max: Math.max,
};

export type FormulaValue = number | string | boolean;
export type FormulaScope = Record<string, FormulaValue>;

interface Token {
  type: 'number' | 'string' | 'identifier' | 'operator';
  value: string;
}

const OPERATORS = [
  '===', '!==', '==', '!=', '>=', '<=', '&&', '||',
  '>', '<', '+', '-', '*', '/', '%', '(', ')', '?', ':', ',', '.', '!',
];

function tokenize(input: string): Token[] {
  const tokens: Token[] = [];
  let i = 0;
  while (i < input.length) {
    const ch = input[i];

    if (/\s/.test(ch)) {
      i++;
      continue;
    }

    if (/[0-9]/.test(ch) || (ch === '.' && /[0-9]/.test(input[i + 1] || ''))) {
      let num = '';
      while (i < input.length && /[0-9.]/.test(input[i])) {
        num += input[i++];
      }
      if (!/^\d*\.?\d+$/.test(num)) {
        throw new FormulaError(`Invalid number literal: ${num}`);
      }
      tokens.push({ type: 'number', value: num });
      continue;
    }

    if (ch === "'" || ch === '"') {
      const quote = ch;
      let str = '';
      i++;
      while (i < input.length && input[i] !== quote) {
        str += input[i++];
      }
      if (i >= input.length) {
        throw new FormulaError('Unterminated string literal.');
      }
      i++; // closing quote
      tokens.push({ type: 'string', value: str });
      continue;
    }

    if (/[A-Za-z_]/.test(ch)) {
      let ident = '';
      while (i < input.length && /[A-Za-z0-9_]/.test(input[i])) {
        ident += input[i++];
      }
      tokens.push({ type: 'identifier', value: ident });
      continue;
    }

    const op = OPERATORS.find((o) => input.startsWith(o, i));
    if (op) {
      tokens.push({ type: 'operator', value: op });
      i += op.length;
      continue;
    }

    throw new FormulaError(`Unexpected character in formula: '${ch}'`);
  }
  return tokens;
}

class Parser {
  private pos = 0;
  private tokens: Token[];
  private scope: FormulaScope;

  constructor(tokens: Token[], scope: FormulaScope) {
    this.tokens = tokens;
    this.scope = scope;
  }

  parse(): FormulaValue {
    const result = this.parseTernary();
    if (this.pos < this.tokens.length) {
      throw new FormulaError(`Unexpected token: '${this.tokens[this.pos].value}'`);
    }
    return result;
  }

  private peek(): Token | undefined {
    return this.tokens[this.pos];
  }

  private matchOperator(...ops: string[]): string | null {
    const token = this.peek();
    if (token && token.type === 'operator' && ops.includes(token.value)) {
      this.pos++;
      return token.value;
    }
    return null;
  }

  private expectOperator(op: string): void {
    if (!this.matchOperator(op)) {
      throw new FormulaError(`Expected '${op}' in formula.`);
    }
  }

  private parseTernary(): FormulaValue {
    const condition = this.parseLogicalOr();
    if (this.matchOperator('?')) {
      const whenTrue = this.parseTernary();
      this.expectOperator(':');
      const whenFalse = this.parseTernary();
      return condition ? whenTrue : whenFalse;
    }
    return condition;
  }

  private parseLogicalOr(): FormulaValue {
    let left = this.parseLogicalAnd();
    while (this.matchOperator('||')) {
      const right = this.parseLogicalAnd();
      left = Boolean(left) || Boolean(right);
    }
    return left;
  }

  private parseLogicalAnd(): FormulaValue {
    let left = this.parseEquality();
    while (this.matchOperator('&&')) {
      const right = this.parseEquality();
      left = Boolean(left) && Boolean(right);
    }
    return left;
  }

  private parseEquality(): FormulaValue {
    let left = this.parseRelational();
    let op: string | null;
    while ((op = this.matchOperator('===', '!==', '==', '!='))) {
      const right = this.parseRelational();
      // Equality is always strict — these are clinical formulas, not JS quizzes.
      left = op === '===' || op === '==' ? left === right : left !== right;
    }
    return left;
  }

  private parseRelational(): FormulaValue {
    let left = this.parseAdditive();
    let op: string | null;
    while ((op = this.matchOperator('>=', '<=', '>', '<'))) {
      const right = this.parseAdditive();
      const l = this.asNumber(left, op);
      const r = this.asNumber(right, op);
      if (op === '>') left = l > r;
      else if (op === '<') left = l < r;
      else if (op === '>=') left = l >= r;
      else left = l <= r;
    }
    return left;
  }

  private parseAdditive(): FormulaValue {
    let left = this.parseMultiplicative();
    let op: string | null;
    while ((op = this.matchOperator('+', '-'))) {
      const right = this.parseMultiplicative();
      const l = this.asNumber(left, op);
      const r = this.asNumber(right, op);
      left = op === '+' ? l + r : l - r;
    }
    return left;
  }

  private parseMultiplicative(): FormulaValue {
    let left = this.parseUnary();
    let op: string | null;
    while ((op = this.matchOperator('*', '/', '%'))) {
      const right = this.parseUnary();
      const l = this.asNumber(left, op);
      const r = this.asNumber(right, op);
      if (op === '*') left = l * r;
      else if (op === '/') left = l / r;
      else left = l % r;
    }
    return left;
  }

  private parseUnary(): FormulaValue {
    if (this.matchOperator('-')) {
      return -this.asNumber(this.parseUnary(), 'unary -');
    }
    if (this.matchOperator('!')) {
      return !this.parseUnary();
    }
    return this.parsePrimary();
  }

  private parsePrimary(): FormulaValue {
    const token = this.peek();
    if (!token) {
      throw new FormulaError('Unexpected end of formula.');
    }

    if (token.type === 'number') {
      this.pos++;
      return parseFloat(token.value);
    }

    if (token.type === 'string') {
      this.pos++;
      return token.value;
    }

    if (this.matchOperator('(')) {
      const value = this.parseTernary();
      this.expectOperator(')');
      return value;
    }

    if (token.type === 'identifier') {
      this.pos++;

      if (token.value === 'Math') {
        return this.parseMathCall();
      }
      if (token.value === 'true') return true;
      if (token.value === 'false') return false;

      // Allow direct calls to math functions like min(a, b), max(a, b), round(a)
      const nextToken = this.peek();
      if (nextToken && nextToken.type === 'operator' && nextToken.value === '(') {
        if (token.value in MATH_FUNCTIONS) {
          this.pos++; // consume '('
          const args: number[] = [];
          if (!this.matchOperator(')')) {
            do {
              args.push(this.asNumber(this.parseTernary(), token.value));
            } while (this.matchOperator(','));
            this.expectOperator(')');
          }
          return MATH_FUNCTIONS[token.value](...args);
        }
      }

      if (!(token.value in this.scope)) {
        throw new FormulaError(`Unknown variable '${token.value}' in formula.`);
      }
      return this.scope[token.value];
    }

    throw new FormulaError(`Unexpected token: '${token.value}'`);
  }

  private parseMathCall(): number {
    this.expectOperator('.');
    const fnToken = this.peek();
    if (!fnToken || fnToken.type !== 'identifier' || !(fnToken.value in MATH_FUNCTIONS)) {
      throw new FormulaError(`Unsupported Math function: '${fnToken?.value ?? ''}'`);
    }
    this.pos++;
    this.expectOperator('(');
    const args: number[] = [];
    if (!this.matchOperator(')')) {
      do {
        args.push(this.asNumber(this.parseTernary(), `Math.${fnToken.value}`));
      } while (this.matchOperator(','));
      this.expectOperator(')');
    }
    return MATH_FUNCTIONS[fnToken.value](...args);
  }

  private asNumber(value: FormulaValue, context: string): number {
    if (typeof value === 'boolean') {
      return value ? 1 : 0;
    }
    if (typeof value !== 'number' || Number.isNaN(value)) {
      throw new FormulaError(`Expected a number for '${context}' but got '${String(value)}'.`);
    }
    return value;
  }
}

/**
 * Evaluate a calculator formula against a scope of input/previous-result values.
 * Throws FormulaError for anything outside the supported grammar.
 */
export function evaluateFormula(formula: string, scope: FormulaScope): FormulaValue {
  if (typeof formula !== 'string' || formula.trim().length === 0) {
    throw new FormulaError('Formula is empty.');
  }
  if (formula.length > 1000) {
    throw new FormulaError('Formula is too long.');
  }
  return new Parser(tokenize(formula), scope).parse();
}

/**
 * Evaluate an ordered list of calculations, feeding each result back into the
 * scope so later formulas can reference earlier ones (e.g. ibw → dosing_weight).
 * Returns 'Error' for any calculation whose formula is invalid.
 */
export function evaluateCalculations(
  calculations: Array<{ id: string; formula: string }>,
  inputs: FormulaScope
): Record<string, FormulaValue | 'Error'> {
  const scope: FormulaScope = { ...inputs };
  const results: Record<string, FormulaValue | 'Error'> = {};
  for (const calc of calculations) {
    try {
      const value = evaluateFormula(calc.formula, scope);
      scope[calc.id] = value;
      results[calc.id] = value;
    } catch {
      results[calc.id] = 'Error';
    }
  }
  return results;
}
